spring.application.name=JavaSpringRelffi
#spring.datasource.url=jdbc:mysql://185.69.152.209:3306/relffi
#spring.jpa.hibernate.ddl-auto=create
#spring.datasource.username=relffi
#spring.datasource.password=relffisql
#spring.jpa.show-sql=true
spring.data.mongodb.uri=mongodb+srv://root:rootroot@cluster0.eamv0ii.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=relffi
